import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const products=[
{id:1,name:'Smart Air Fryer 5.5L',cat:'Home & Kitchen',price:7499,tag:'Popular',img:'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=900&q=85'},
{id:2,name:'Electric Kettle 1.7L',cat:'Home & Kitchen',price:2499,tag:'Everyday',img:'https://images.unsplash.com/photo-1594213114663-d94db9b1718a?auto=format&fit=crop&w=900&q=85'},
{id:3,name:'Modern Countertop Blender',cat:'Home & Kitchen',price:3999,tag:'New',img:'https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=900&q=85'},
{id:4,name:'Wireless Bluetooth Headphones',cat:'Electronics',price:4999,tag:'Top Rated',img:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85'},
{id:5,name:'Smart LED TV 43-inch',cat:'Electronics',price:34999,tag:'Featured',img:'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=900&q=85'},
{id:6,name:'Portable Bluetooth Speaker',cat:'Electronics',price:5499,tag:'Hot',img:'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=85'},
{id:7,name:'Wireless Keyboard & Mouse',cat:'Computer Accessories',price:3299,tag:'Work',img:'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=85'},
{id:8,name:'USB-C Laptop Dock',cat:'Computer Accessories',price:6999,tag:'New',img:'https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=900&q=85'},
{id:9,name:'Ergonomic Office Monitor',cat:'Computer Accessories',price:21999,tag:'Work',img:'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=85'},
{id:10,name:'Laptop Backpack',cat:'Computer Accessories',price:3999,tag:'Travel',img:'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=85'},
{id:11,name:'Digital Microwave Oven',cat:'Home & Kitchen',price:10999,tag:'Home',img:'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?auto=format&fit=crop&w=900&q=85'},
{id:12,name:'Smartwatch Fitness Edition',cat:'Electronics',price:6499,tag:'Trending',img:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=85'}
];
const money=n=>`KES ${n.toLocaleString()}`;
function App(){
 const [query,setQuery]=useState(''); const [cat,setCat]=useState('All'); const [cart,setCart]=useState([]); const [openCart,setOpenCart]=useState(false); const [checkout,setCheckout]=useState(false); const [notice,setNotice]=useState('');
 const filtered=useMemo(()=>products.filter(p=>(cat==='All'||p.cat===cat)&&p.name.toLowerCase().includes(query.toLowerCase())),[query,cat]);
 const add=p=>{setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,q:i.q+1}:i):[...c,{...p,q:1}]});setNotice(`${p.name} added to cart`);setTimeout(()=>setNotice(''),1800)};
 const change=(id,d)=>setCart(c=>c.map(i=>i.id===id?{...i,q:Math.max(0,i.q+d)}:i).filter(i=>i.q));
 const total=cart.reduce((s,i)=>s+i.price*i.q,0); const count=cart.reduce((s,i)=>s+i.q,0);
 return <div>
 <header className="top"><div className="nav wrap"><a className="brand" href="#home"><span className="logo">W</span><span>Wide City <b>Smart Digital Homes</b></span></a><nav><a href="#shop">Shop</a><a href="#categories">Categories</a><a href="#why">Why us</a></nav><button className="cartBtn" onClick={()=>setOpenCart(true)} aria-label={`Cart with ${count} items`}>🛒 <span>Cart</span>{count>0&&<i>{count}</i>}</button></div></header>
 <main id="home">
 <section className="hero wrap"><div className="heroText"><p className="eyebrow">SMART LIVING • SIMPLE SHOPPING</p><h1>Better technology for <span>everyday living.</span></h1><p className="lead">Shop trusted home appliances, electronics and computer accessories — selected for modern Kenyan homes and workspaces.</p><div className="heroActions"><a className="primary" href="#shop">Shop products</a><a className="secondary" href="#why">How it works</a></div><div className="trust"><span>✓ Secure M-Pesa checkout</span><span>✓ Easy product search</span><span>✓ Friendly support</span></div></div><div className="heroCard"><img src="https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=85" alt="Modern online shopping"/><div><strong>Pay with M-Pesa</strong><small>Choose your items, enter your number and receive an STK prompt.</small></div></div></section>
 <section id="categories" className="wrap categories"><div className="sectionHead"><div><p className="eyebrow">BROWSE BY NEED</p><h2>Shop by category</h2></div></div><div className="catGrid">{['Home & Kitchen','Computer Accessories','Electronics'].map((c,i)=><button key={c} className="catCard" onClick={()=>{setCat(c);document.querySelector('#shop').scrollIntoView({behavior:'smooth'})}}><span>{['🏠','💻','⚡'][i]}</span><strong>{c}</strong><small>Explore products →</small></button>)}</div></section>
 <section id="shop" className="wrap shop"><div className="sectionHead"><div><p className="eyebrow">THE E STORE</p><h2>Find what you need</h2></div><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search appliances, electronics..." aria-label="Search products"/></div></div><div className="filters"><button className={cat==='All'?'active':''} onClick={()=>setCat('All')}>All</button>{['Home & Kitchen','Computer Accessories','Electronics'].map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><div className="products">{filtered.map(p=><article className="product" key={p.id}><div className="pic"><img src={p.img} alt={p.name}/><span>{p.tag}</span></div><div className="pbody"><small>{p.cat}</small><h3>{p.name}</h3><div className="priceRow"><strong>{money(p.price)}</strong><button onClick={()=>add(p)}>Add to cart</button></div></div></article>)}</div>{!filtered.length&&<div className="empty">No products matched “{query}”. Try another search.</div>}</section>
 <section id="why" className="why wrap"><div><p className="eyebrow">DESIGNED AROUND YOU</p><h2>Simple, clear and human-centered.</h2><p>Every step is designed around core HCI principles: visibility, consistency, feedback, recognition over recall, accessibility and error prevention.</p></div><div className="whyGrid"><div><b>01</b><strong>Clear navigation</strong><span>Categories and search make products easy to discover.</span></div><div><b>02</b><strong>Immediate feedback</strong><span>Cart actions and payment states keep customers informed.</span></div><div><b>03</b><strong>Low-friction checkout</strong><span>M-Pesa STK Push reduces manual payment steps.</span></div><div><b>04</b><strong>Responsive design</strong><span>Comfortable shopping on phone, tablet or desktop.</span></div></div></section>
 </main><footer><div className="wrap footer"><div><div className="brand"><span className="logo">W</span><span>Wide City <b>Smart Digital Homes</b></span></div><p>Smart products for smart living.</p></div><div><strong>Store</strong><a href="#shop">All products</a><a href="#categories">Categories</a></div><div><strong>Payment</strong><span>M-Pesa STK Push</span><span>Secure checkout</span></div></div><div className="copyright">© 2026 Wide City Smart Digital Homes. Built for modern Kenyan shoppers.</div></footer>
 {notice&&<div className="toast">✓ {notice}</div>}
 {openCart&&<div className="overlay" onClick={()=>setOpenCart(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawerHead"><h2>Your cart</h2><button onClick={()=>setOpenCart(false)}>×</button></div>{!cart.length?<div className="cartEmpty"><span>🛒</span><h3>Your cart is empty</h3><p>Add products you love and they’ll appear here.</p><button className="primary" onClick={()=>setOpenCart(false)}>Continue shopping</button></div>:<><div className="cartItems">{cart.map(i=><div className="cartItem" key={i.id}><img src={i.img}/><div><strong>{i.name}</strong><small>{money(i.price)}</small><div className="qty"><button onClick={()=>change(i.id,-1)}>−</button><span>{i.q}</span><button onClick={()=>change(i.id,1)}>+</button></div></div><b>{money(i.price*i.q)}</b></div>)}</div><div className="summary"><div><span>Subtotal</span><strong>{money(total)}</strong></div><small>Delivery charges can be confirmed before dispatch.</small><button className="primary full" onClick={()=>{setOpenCart(false);setCheckout(true)}}>Proceed to M-Pesa</button></div></>}</aside></div>}
 {checkout&&<Checkout total={total} onClose={()=>setCheckout(false)} onDone={()=>{setCheckout(false);setCart([])}}/>}
 </div>
}
function Checkout({total,onClose,onDone}){const [phone,setPhone]=useState('');const [loading,setLoading]=useState(false);const [msg,setMsg]=useState('');const submit=async e=>{e.preventDefault();setLoading(true);setMsg('');try{const r=await fetch('/api/mpesa/stkpush',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone,amount:Math.round(total)})});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not start payment');setMsg(d.message||'STK Push sent. Check your phone and enter your M-Pesa PIN.');}catch(err){setMsg(err.message)}finally{setLoading(false)}};return <div className="modalWrap"><div className="modal"><button className="close" onClick={onClose}>×</button><div className="mpesaIcon">M</div><p className="eyebrow">SECURE CHECKOUT</p><h2>Pay {money(total)} with M-Pesa</h2><p>Enter the Safaricom number that should receive the payment prompt.</p><form onSubmit={submit}><label>Phone number<input required inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="0712 345 678"/></label><button className="primary full" disabled={loading}>{loading?'Sending STK prompt…':'Send M-Pesa STK prompt'}</button></form>{msg&&<div className="payMsg">{msg}</div>}<small className="security">Your Daraja credentials stay on the server and are never exposed to the browser.</small></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
